language: generic
sudo: true
dist: trusty

# whitelist of branches to build
branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq make xsltproc

script:
  - cd schemas && make && cd -
  - git clone https://github.com/commoncriteria/commoncriteria.github.io.git
  - git clone https://github.com/commoncriteria/ci-scripts.git
  - mkdir -p commoncriteria.github.io/pp/$(basename $TRAVIS_REPO_SLUG)
  - cp schemas/CCProtectionProfile.html commoncriteria.github.io/pp/$(basename $TRAVIS_REPO_SLUG)
  - cd commoncriteria.github.io
  - git add --all && git commit -m "Deploying changes"
  - git pull --rebase
  - cd -
  
# Deploy HTML pages and updated index.html (needed before we can generate pdf versions)
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: commoncriteria.github.io/
  repo: commoncriteria/commoncriteria.github.io
  target_branch: master
  on:
    branch: master
